### ISSUE TITLE
class='icon-pencil' is broken

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/wn-tailwindui-plugin#12]
A backend button with class `icon-pencil` doesn't render the icon, it renders a square with a cross in it
![image](https://user-images.githubusercontent.com/89913092/186401035-1759dc41-9c8f-4671-a50e-f72f705cabd6.png)

```
<button
    class="btn btn-primary icon-pencil"
    data-request="<?= $this->getEventHandler('onEdit'); ?>"
    data-request-data="id: <?= $id; ?>"
    title="Edit">
</button>
```

**Comment by LukeTowers** [comment]
@AIC-BV does this occur with this plugin disabled?

**Comment by AIC-BV** [comment]
@LukeTowers When the plugin is disabled (removed from composer) the icon works perfectly fine!

**Comment by LukeTowers** [comment]
@AIC-BV is this still an issue?

**Comment by AIC-BV** [comment]
@LukeTowers Yes it is still broken

**Comment by AIC-BV** [comment]
Seems to be fine by now
