### ISSUE TITLE
Widget settings icon is gone

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/wn-tailwindui-plugin#16]
![image](https://user-images.githubusercontent.com/89913092/189917631-63db9846-3a23-4ff6-955f-314094df07c8.png)
The settings cog is gone and you can no longer edit its properties

**Comment by LukeTowers** [comment]
It's from https://github.com/wintercms/wn-tailwindui-plugin/blob/main/assets/css/src/custom.css#L69-L74, you can probably make a PR to remove those lines and we'll just re-add them to the specific page they were meant for on our project.

**Comment by AIC-BV** [comment]
I think this has been resolved?
