### ISSUE TITLE
Sticky navigation overflow bug

### ISSUE THREAD

**Issue by damsfx** [wintercms/wn-tailwindui-plugin#22]
The #20 PR introduces a display bug for me.  
The sidenav layout overflow the content layout : 
![image](https://user-images.githubusercontent.com/282242/209566963-0b4d53f4-fc2b-4203-a48c-378b558fe3e8.png)

@joseph-sm can you test it with the default WinterCMS logo?

**Comment by joseph-sm** [comment]
@damsfx Apologies have been on annual leave, I am having trouble replicating this locally, I plan to do another pass on the layout / navigation especially in regards to z-index issues in the next week or two.

**Comment by LukeTowers** [comment]
This should be fixed by the most recent merged PRs
