### ISSUE TITLE
Scrollbars visible on each page

### ISSUE THREAD

**Issue by damsfx** [wintercms/wn-tailwindui-plugin#3]
Using `@apply h-screen` for the `layout` container, gives me scrollbars in every backend pages.  
https://github.com/wintercms/wn-tailwindui-plugin/blob/a34b50bd0273c1a6950ba147b08950e09b2ff968/assets/css/src/custom.css#L140
![image](https://user-images.githubusercontent.com/282242/176249074-f720fc85-60bf-4553-9798-d4dd02fba173.png)

Tested on Windows on Firefox, Edge and Chrome.  

Replacing it with `height : calc(100vh - 4rem)` remove the scrollbars.
Need to remove `layout-topmenu` container's height.

**Comment by mjauvin** [comment]
wouldn't that only remove the vertical scrollbar @damsfx ?

**Comment by mjauvin** [comment]
never mind, the verticall scrollbar itself make the width too large and that by itself adds the horizontal scrollbar as well...

**Comment by damsfx** [comment]
> change:
> to use `w-full` rather than `w-screen`

@LukeTowers Do you think you have time to make this change or do you prefer a PR?
