### ISSUE TITLE
Missing backend JS files

### ISSUE THREAD

**Issue by Monologophobia** [wintercms/wn-tailwindui-plugin#31]
### Winter CMS Build
1.2.1

### PHP Version
8.1.13

### Database engine
sqlite / any

### Plugins installed
wn-tailwindui-plugin

### Issue description
Installing this plugin removes 
```
/modules/system/assets/js/build/system.debug.js
/modules/backend/assets/ui/js/build/manifest.js
/modules/backend/assets/ui/js/build/vendor.js
```
This prevents `$.request` as CSRF header is not added to AJAX requests.

### Steps to replicate
```
composer create-project wintercms/winter
```
At this point, the files are intact.
```
composer require winter/wn-tailwindui-plugin
```
Now the files are missing.

Login to backend check network requests
![image](https://user-images.githubusercontent.com/8427249/217199407-751be0fc-201f-496b-80ba-d4f2cb6d36ac.png)
![image](https://user-images.githubusercontent.com/8427249/217199561-47dfb955-92ec-4389-82c9-2d2699fcc03b.png)

### Workaround
Download the above files from the main repository or use `composer require winter/wn-tailwindui-plugin:dev-main#ed9af5c` which was the last commit before the changes.

**Comment by Monologophobia** [comment]
Sorry, slight correction. It's not that the files are removed, it's just that they don't exist in 1.2.1. I assume this means this wn-tailwindui-plugin:dev-main is only compatible with wintercms:develop rather than 1.2.1?

**Comment by josephcrowell** [comment]
Yep change the references to the Winter CMS core files to "dev-develop" in your composer.json.

**Comment by Monologophobia** [comment]
@josephcrowell Thanks for the confirmation.

May be worth mentioning this in the README but that may be a tad excessive as it's an in-dev plugin without a stable version yet.

**Comment by bennothommo** [comment]
It's come up a couple of times now, so I've added a note in the README to use the `develop` branch of Winter. Thanks @Monologophobia :)
