### ISSUE TITLE
Primary & secondary vars not available during compile time

### ISSUE THREAD

**Issue by LukeTowers** [wintercms/wn-tailwindui-plugin#4]
The color-mod function requires the --primary & --secondary CSS vars to be present during compile time which fails under the current configuration rendering any color-mod defined colours unavailable at the moment.

A couple of different options are available:
- Find a way to inject variables during the compilation process and require each project using this plugin to recompile the styles for themselves
- Perform colour modifications in PHP and inject them as root CSS variables like we're doing now with primary & secondary and then refer to those variables in the tailwind.config.js file. (This is my preferred solution).

@joseph-sm @jaxwilko thoughts?

**Comment by jaxwilko** [comment]
We could modify the mix config generator to allow for custom vars to be passed into webpack, which should allow for those vars to be used at compile time. It may get a little bit messy though

**Comment by LukeTowers** [comment]
Yeah, still not a fan of that approach, especially when you factor in that the branding settings could be changed dynamically per request, especially in multi-tenant projects. You'd have to compile the assets once per tenant and switch between them, sounds like a nightmare.

**Comment by LukeTowers** [comment]
Fixed by https://github.com/wintercms/wn-tailwindui-plugin/commit/9604d918c5b280d73df15c1c0e5ffdb8f4134190
