### ISSUE TITLE
Snippets do not display in the Static Page plugin

### ISSUE THREAD

**Issue by SummerstarDev** [wintercms/wn-tailwindui-plugin#40]
When using TailwindUI the snippets column doesn't display any of the snippets with codes assigned in the CMS partials. When disabling this plugin and using the default backend, these snippets appear again.

**Comment by bennothommo** [comment]
Hi @SummerstarDev, thanks for the report. Could you provide some screenshots of how it appears in Tailwind UI vs the standard backend, so we can compare?

**Comment by SummerstarDev** [comment]
![image](https://github.com/wintercms/wn-tailwindui-plugin/assets/140378015/9affe663-a088-4d29-8e54-7a2141e5fc7f)
![image](https://github.com/wintercms/wn-tailwindui-plugin/assets/140378015/c537026d-7e5a-4cf8-8e25-a514709139ff)

**Comment by SummerstarDev** [comment]
There is no search bar either, just blank both dark mode and white mode.

**Comment by LukeTowers** [comment]
This was fixed in https://github.com/wintercms/wn-pages-plugin/commit/e8dbc3ba2a5fe253f5d7a6918828e86846bb7f1e, I'll make a new release for that plugin.
